---
- name: Find existing files
  become: true
  shell: rm -rf *
  tags: minio-cluster

- name: Copy script
  template:
    src: "create-cluster.sh.j2"
    dest: "/home/{{ user }}/create-cluster.sh"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
  tags: minio-cluster

- name: Copy config
  template:
    src: "config.yml.j2"
    dest: "/home/{{ user }}/config.yml"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
  tags: minio-cluster

- name: Copy env
  template:
    src: "minio.env"
    dest: "/etc/default/minio"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
  tags: files

- name: Copy service
  template:
    src: "minio.service"
    dest: "/etc/systemd/system/minio.service"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
  tags: files

- name: Find files to modify - create
  find:
    paths: "/home/{{ user }}"
    patterns: "*.sh"
    recurse: no
  register: repos
  tags: minio-cluster

- name: Replace host - create
  replace:
    path: "{{ item.path }}"
    regexp: 'HOSTNAME'
    replace: '{{ inventory_hostname }}'
  with_items: "{{ repos.files }}"
  tags: minio-cluster

- name: Replace host short - create
  replace:
    path: "{{ item.path }}"
    regexp: 'HOSTSHORT'
    replace: '{{ inventory_hostname_short }}'
  with_items: "{{ repos.files }}"
  tags: minio-cluster

- name: Find files to modify - env
  find:
    paths: "/etc/default"
    patterns: "minio"
    recurse: no
  register: env
  tags: minio-cluster

- name: Replace host - env - SCHEMA
  replace:
    path: "{{ item.path }}"
    regexp: 'SCHEMA'
    replace: '{{ schema }}'
  with_items: "{{ env.files }}"
  tags: minio-cluster

- name: Replace host - env - HOST_PREFIX
  replace:
    path: "{{ item.path }}"
    regexp: 'HOST_PREFIX'
    replace: '{{ host_prefix }}'
  with_items: "{{ env.files }}"
  tags: minio-cluster

- name: Replace host - env - HOST_DOMAIN
  replace:
    path: "{{ item.path }}"
    regexp: 'HOST_DOMAIN'
    replace: '{{ host_domain }}'
  with_items: "{{ env.files }}"
  tags: minio-cluster

- name: Replace host - env - API_PORT
  replace:
    path: "{{ item.path }}"
    regexp: 'API_PORT'
    replace: '{{ api_port }}'
  with_items: "{{ env.files }}"
  tags: minio-cluster

- name: Replace host - env - CONSOLE_PORT
  replace:
    path: "{{ item.path }}"
    regexp: 'CONSOLE_PORT'
    replace: '{{ console_port }}'
  with_items: "{{ env.files }}"
  tags: minio-cluster

- name: Run install
  become: true
  become_user: "{{ user }}"
  shell: ./create-cluster.sh
  tags: minio-cluster